name: run tests inside docker container

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "Inner parameter for Allure TestOps"
        required: false

env:
  ALLURE_ENDPOINT: https://demo.testops.cloud
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN_TESTING }}
  ALLURE_PROJECT_ID: 276
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_JOB_UID: ${GITHUB_REPOSITORY}/actions/workflows/${{ result.data.workflow_id }}

jobs:
  steps:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v4
        id: allure-job-uid
        with:
          result-encoding: string
          script: |
            const result = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            return `${context.repo.owner}/${context.repo.repo}/actions/workflows/${result.data.workflow_id}`
      - name: Prepare env file for Docker container
        run: printenv | grep "ALLURE\|GITHUB" > env.list
      - name: Add allurectl to Docker container
        run: docker build . -t openjdk:8-allurectl
      - name: Run autotests in docker allurectl
        run: |
          echo ${ALLURE_JOB_UID}
#          docker run --volume "$(pwd)":/github/workspace \
#                     --workdir=/github/workspace \
#                     --env-file env.list \
#                     openjdk:8-allurectl \
#                     allurectl watch --results build/allure-results -- ./gradlew clean test